/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tubespbo;
import javax.swing.*;
import java.sql.*;
import java.awt.*;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LEGION
 */
public class Beranda extends javax.swing.JFrame {
    DefaultListModel dlm = new DefaultListModel();
    JDBC conn; 
    int idKereta, hargaTiket,q, id;
    String namaKereta, gerbong, kelas, jadwalBerangkat, jadwalTiba, stasiunAsal, stasiunTujuan, namas, umurs, jenisKelamins;
    ArrayList<Kereta> kereta = new ArrayList<>();
    Pembeli pembelis = new Pembeli();
    
    
    /**
     * Creates new form Beranda
     */
    public Beranda(Pembeli pembelis) {
        initComponents();
        try{
            Connection koneksi;
            conn = new JDBC();
            koneksi = conn.connectDB();
            Statement stmt = koneksi.createStatement();
            String sql = "SELECT * FROM kereta";
            ResultSet rs = stmt.executeQuery(sql);
            namas = pembelis.getNama();
            umurs = pembelis.getUmur();
            jenisKelamins = pembelis.getJenisKelamin();
            nama.setText(namas);
            umur.setText(pembelis.getUmur());
            showTiket(namas);
            jenisKelamin.setText(pembelis.getJenisKelamin());
            while(rs.next()){
                dlm.addElement(rs.getString("namaKereta"));
            }
            listKA.setModel(dlm);
                
        } catch(SQLException e){
            e.printStackTrace();
        }
    }

    private Beranda() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        etrainText = new javax.swing.JLabel();
        listKAText = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listKA = new javax.swing.JList<>();
        tujuanLabel = new javax.swing.JLabel();
        namaKeretaLabel = new javax.swing.JLabel();
        gerbongLabel = new javax.swing.JLabel();
        kelasLabel = new javax.swing.JLabel();
        berangkatLabel = new javax.swing.JLabel();
        tibaLabel = new javax.swing.JLabel();
        hargaLabel = new javax.swing.JLabel();
        asalLabel = new javax.swing.JLabel();
        etrainText1 = new javax.swing.JLabel();
        nama = new javax.swing.JTextField();
        tibaLabel1 = new javax.swing.JLabel();
        tibaLabel2 = new javax.swing.JLabel();
        umur = new javax.swing.JTextField();
        tibaLabel3 = new javax.swing.JLabel();
        jenisKelamin = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        etrainText2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        etrainText.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        etrainText.setText("DAFTAR TIKET");

        listKAText.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        listKAText.setText("LIST KERETA API");

        listKA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listKAMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listKA);

        tujuanLabel.setText("Stasiun Tujuan : ");

        namaKeretaLabel.setText("Nama Kereta Api :  ");

        gerbongLabel.setText("Gerbong : ");

        kelasLabel.setText("Kelas : ");

        berangkatLabel.setText("Jadwal Berangkat : ");

        tibaLabel.setText("Jadwal Tiba : ");

        hargaLabel.setText("Harga Tiket : ");

        asalLabel.setText("Stasiun Asal : ");

        etrainText1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        etrainText1.setText("E-TRAIN ");

        nama.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                namaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                namaFocusLost(evt);
            }
        });
        nama.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                namaInputMethodTextChanged(evt);
            }
        });

        tibaLabel1.setText("Nama Lengkap");

        tibaLabel2.setText("Umur");

        tibaLabel3.setText("Jenis Kelamin");

        jButton1.setText("UPDATE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "id", "Nama Penumpang", "Umur", "Jenis Kelamin", "Nama Kereta", "Gerbong", "Kelas", "Jadwal Berangkat", "Stasiun Asal", "Stasiun Tujuan"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        etrainText2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        etrainText2.setText("PEMBELIAN TIKET");

        jButton2.setText("BELI TIKET");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("DELETE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("REFRESH");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(etrainText)
                    .addComponent(listKAText)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 636, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 952, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(berangkatLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 381, Short.MAX_VALUE)
                                            .addComponent(tibaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(hargaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(asalLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(tujuanLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(kelasLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(gerbongLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tibaLabel1)
                                            .addComponent(tibaLabel2)
                                            .addComponent(tibaLabel3))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(nama, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(umur)
                                            .addComponent(jenisKelamin, javax.swing.GroupLayout.Alignment.LEADING)))
                                    .addComponent(namaKeretaLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(26, 26, 26))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 159, Short.MAX_VALUE)
                        .addComponent(etrainText2)
                        .addGap(128, 128, 128))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(etrainText1)
                .addGap(584, 584, 584))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(190, 190, 190)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(175, 175, 175)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(157, 157, 157))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(etrainText1)
                        .addGap(14, 14, 14)
                        .addComponent(etrainText2)
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tibaLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(umur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tibaLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jenisKelamin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tibaLabel3))
                        .addGap(18, 18, 18)
                        .addComponent(namaKeretaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(listKAText)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                        .addComponent(gerbongLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(kelasLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(berangkatLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tibaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(hargaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(asalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(etrainText)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tujuanLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listKAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listKAMouseClicked
        // TODO add your handling code here:
        for(int i=0; i<dlm.getSize(); i++){
            if(listKA.isSelectedIndex(i)){
                try{
                    Connection koneksi;
                    conn = new JDBC();
                    koneksi = conn.connectDB();
                    Statement stmt = koneksi.createStatement();
                    String sql = "SELECT * FROM kereta";
                    ResultSet rs = stmt.executeQuery(sql);
                    
                    while(rs.next()){
                        if(rs.getString("namaKereta").equals(dlm.get(i))){
                            idKereta = rs.getInt("idKereta");
                            
                            namaKeretaLabel.setText("Nama Kereta : " + rs.getString("namaKereta"));
                            namaKereta = rs.getString("namaKereta");
                            
                            gerbongLabel.setText("Gerbong : " + rs.getString("gerbong"));
                            gerbong = rs.getString("gerbong");
                            
                            kelasLabel.setText("Kelas : " + rs.getString("kelas"));
                            kelas = rs.getString("kelas");
                            
                            berangkatLabel.setText("Jadwal Berangkat : " + rs.getString("jadwalBerangkat"));
                            jadwalBerangkat = rs.getString("jadwalBerangkat");
                            
                            tibaLabel.setText("Jadwal Tiba : " + rs.getString("jadwalTiba"));
                            jadwalTiba = rs.getString("jadwalTiba");
                            
                            hargaLabel.setText("Harga Tiket : " + rs.getInt("hargaTiket"));
                            hargaTiket = rs.getInt("hargaTiket");
                            
                            asalLabel.setText("Stasiun Asal : " + rs.getString("stasiunAsal"));
                            stasiunAsal = rs.getString("stasiunAsal");
                            
                            tujuanLabel.setText("Stasiun Tujuan : " + rs.getString("stasiunTujuan"));
                            stasiunTujuan = rs.getString("stasiunTujuan");
                        }
                    }
                } catch(SQLException e){
                    e.printStackTrace();
                }
            }
        }

    }//GEN-LAST:event_listKAMouseClicked

    private void namaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_namaFocusGained
        // TODO add your handling code here:

    }//GEN-LAST:event_namaFocusGained

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if(namaKereta == null ){
            JOptionPane.showMessageDialog(this, "Silahkan pilih kereta terlebih dahulu !", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else{
            String namaPenumpang = nama.getText().toString();
            String umurPenumpang = umur.getText().toString();
            String jenisKelaminPenumpang = jenisKelamin.getText().toString();
            
            pembelis.pembelian(namas,namaPenumpang, umurPenumpang, jenisKelaminPenumpang, namaKereta, gerbong, kelas, jadwalTiba, jadwalTiba, stasiunAsal, stasiunTujuan);
            JOptionPane.showMessageDialog(this, "Selamat tiket berhasil dibeli ", "Error", JOptionPane.INFORMATION_MESSAGE);
            showTiket(namas);
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed
public void showTiket(String nama){
      Connection koneksi = conn.connectDB();
        try {
            PreparedStatement ps = (PreparedStatement)koneksi.prepareStatement("SELECT * FROM tiket WHERE nama_penumpang = ?");
            ps.setString(1, nama);
          
            ResultSet rs = ps.executeQuery();
   
            ResultSetMetaData stData = rs.getMetaData();
            q = stData.getColumnCount();
            DefaultTableModel RecordTable = (DefaultTableModel)jTable1.getModel();
            RecordTable.setRowCount(0);
            
            while(rs.next()){
                Vector columdData = new Vector();
                for(int i = 1;i <= q; i++ ){
                    columdData.add(rs.getString("id"));
                    columdData.add(rs.getString("nama_penumpangs"));
                    columdData.add(rs.getString("umur"));
                    columdData.add(rs.getString("jenis_kelamin"));
                    columdData.add(rs.getString("nama_kereta"));
                    columdData.add(rs.getString("gerbong"));
                    columdData.add(rs.getString("kelas"));
                    columdData.add(rs.getString("jadwal_berangkat"));
                    columdData.add(rs.getString("jadwal_tiba"));
                    columdData.add(rs.getString("stasiun_asal"));
                    columdData.add(rs.getString("stasiun_tujuan"));
                
                }
                RecordTable.addRow(columdData);
            }
          
          
        } catch (SQLException ex) {
            Logger.getLogger(Penumpang.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
       showTiket(namas);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
   
        int selectedRows = jTable1.getSelectedRow();
        System.out.println(selectedRows);
        if(selectedRows <0 ){
            JOptionPane.showMessageDialog(this, "Silahkan pilih data pada tabel terlebih dahulu !", "Error", JOptionPane.ERROR_MESSAGE);
        }else{
              try {
           
                 DefaultTableModel RecordTable = (DefaultTableModel)jTable1.getModel();
             id = Integer.parseInt(RecordTable.getValueAt(selectedRows, 0).toString());
            int deleteItem = JOptionPane.showConfirmDialog(null, "Yakin Refund Tiket ?",
                    "Warning", JOptionPane.YES_NO_OPTION);
            if(deleteItem == JOptionPane.YES_OPTION){
                pembelis.refund(id);
                
                showTiket(namas);
            }
            
        } catch (Exception e) {
        
            }
        }
      
       
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        DefaultTableModel RecordTable = (DefaultTableModel)jTable1.getModel();
        int selectedRows = jTable1.getSelectedRow();
        nama.setText(RecordTable.getValueAt(selectedRows, 1).toString());
        umur.setText(RecordTable.getValueAt(selectedRows, 2).toString());
        jenisKelamin.setText(RecordTable.getValueAt(selectedRows, 3).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    private void namaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_namaFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_namaFocusLost

    private void namaInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_namaInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_namaInputMethodTextChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
            int selectedRows = jTable1.getSelectedRow();
            String namaPenumpang = nama.getText().toString();
            String umurPenumpang = umur.getText().toString();
            String jenisKelaminPenumpang = jenisKelamin.getText().toString();
            System.out.println(selectedRows);
        if(selectedRows <0 || namaKereta == null ){
            JOptionPane.showMessageDialog(this, "Silahkan pilih data pada tabel dan list kereta terlebih dahulu !", "Error", JOptionPane.ERROR_MESSAGE);
        }else{
            
               int deleteItem = JOptionPane.showConfirmDialog(null, "Yakin ingin mengedit Tiket ?",
                    "Warning", JOptionPane.YES_NO_OPTION);
            if(deleteItem == JOptionPane.YES_OPTION){
                DefaultTableModel RecordTable = (DefaultTableModel)jTable1.getModel();
                id = Integer.parseInt(RecordTable.getValueAt(selectedRows, 0).toString());
                pembelis.EditTiket(id,namaPenumpang, umurPenumpang, jenisKelaminPenumpang, namaKereta, gerbong, kelas, jadwalTiba, jadwalTiba, stasiunAsal, stasiunTujuan);
                
                showTiket(namas);
            }
        }
          
           
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Beranda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Beranda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Beranda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Beranda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Beranda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel asalLabel;
    private javax.swing.JLabel berangkatLabel;
    private javax.swing.JLabel etrainText;
    private javax.swing.JLabel etrainText1;
    private javax.swing.JLabel etrainText2;
    private javax.swing.JLabel gerbongLabel;
    private javax.swing.JLabel hargaLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jenisKelamin;
    private javax.swing.JLabel kelasLabel;
    private javax.swing.JList<String> listKA;
    private javax.swing.JLabel listKAText;
    private javax.swing.JTextField nama;
    private javax.swing.JLabel namaKeretaLabel;
    private javax.swing.JLabel tibaLabel;
    private javax.swing.JLabel tibaLabel1;
    private javax.swing.JLabel tibaLabel2;
    private javax.swing.JLabel tibaLabel3;
    private javax.swing.JLabel tujuanLabel;
    private javax.swing.JTextField umur;
    // End of variables declaration//GEN-END:variables
}
