/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tubespbo;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LEGION
 */
public class DashboardAdmin extends javax.swing.JFrame {

    /**
     * Creates new form UpdateKereta
     */
    JDBC conn;
    int idKereta, hargaTiket, q;
    String namaKereta, gerbong, kelas, jadwalBerangkat, jadwalTiba, stasiunAsal, stasiunTujuan;
    Kereta kereta = new Kereta(idKereta, hargaTiket, namaKereta, gerbong, kelas, jadwalBerangkat, jadwalTiba, stasiunAsal, stasiunTujuan);
    public DashboardAdmin() {
        initComponents();
        conn = new JDBC();
        showDaftarKereta();
        if(conn == null){
            JOptionPane.showMessageDialog(this, "Tidak bisa menyambungkan ke database!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dashboardAdmin = new javax.swing.JLabel();
        namaKeretaLabel = new javax.swing.JLabel();
        inputGerbong = new javax.swing.JTextField();
        gerbongLabel = new javax.swing.JLabel();
        inputNamaKereta = new javax.swing.JTextField();
        kelasLabel = new javax.swing.JLabel();
        inputKelas = new javax.swing.JTextField();
        inputJadwalBerangkat = new javax.swing.JTextField();
        jadwalBerangkatLabel = new javax.swing.JLabel();
        jadwalTibaLabel = new javax.swing.JLabel();
        inputJadwalTiba = new javax.swing.JTextField();
        inputHargaTiket = new javax.swing.JTextField();
        hargaTiketLabel = new javax.swing.JLabel();
        stasiunAsalLabel = new javax.swing.JLabel();
        inputStasiunAsal = new javax.swing.JTextField();
        stasiunTujuanLabel = new javax.swing.JLabel();
        inputStasiunTujuan = new javax.swing.JTextField();
        tambahButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        dashboardAdmin.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        dashboardAdmin.setText("DASHBOARD ADMIN");

        namaKeretaLabel.setText("Nama Kereta");

        inputGerbong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputGerbongActionPerformed(evt);
            }
        });

        gerbongLabel.setText("Gerbong");

        inputNamaKereta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputNamaKeretaActionPerformed(evt);
            }
        });

        kelasLabel.setText("Kelas");

        inputKelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputKelasActionPerformed(evt);
            }
        });

        inputJadwalBerangkat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputJadwalBerangkatActionPerformed(evt);
            }
        });

        jadwalBerangkatLabel.setText("Jadwal Berangkat");

        jadwalTibaLabel.setText("Jadwal Tiba");

        inputJadwalTiba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputJadwalTibaActionPerformed(evt);
            }
        });

        inputHargaTiket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputHargaTiketActionPerformed(evt);
            }
        });

        hargaTiketLabel.setText("Harga Tiket");

        stasiunAsalLabel.setText("Stasiun Asal");

        inputStasiunAsal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputStasiunAsalActionPerformed(evt);
            }
        });

        stasiunTujuanLabel.setText("Stasiun Tujuan");

        inputStasiunTujuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputStasiunTujuanActionPerformed(evt);
            }
        });

        tambahButton.setText("TAMBAH");
        tambahButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahButtonActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id Kereta", "Nama Kereta", "Gerbong", "Kelas", "Jadwal Berangkat", "Jadwal Tiba", "Harga Tiket", "Stasiun Asal", "Stasiun Tujuan"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setHeaderValue("Id Kereta");
        }

        jButton1.setText("UPDATE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("DELETE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("REFRESH");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(namaKeretaLabel)
                            .addComponent(gerbongLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kelasLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inputNamaKereta)
                            .addComponent(inputGerbong)
                            .addComponent(inputKelas)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jadwalBerangkatLabel)
                            .addComponent(stasiunTujuanLabel)
                            .addComponent(stasiunAsalLabel)
                            .addComponent(hargaTiketLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jadwalTibaLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inputJadwalTiba)
                            .addComponent(inputJadwalBerangkat)
                            .addComponent(inputHargaTiket)
                            .addComponent(inputStasiunAsal)
                            .addComponent(inputStasiunTujuan))))
                .addGap(48, 48, 48))
            .addGroup(layout.createSequentialGroup()
                .addGap(152, 152, 152)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(164, 164, 164)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(154, 154, 154))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 892, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(dashboardAdmin)
                        .addGap(355, 355, 355))))
            .addGroup(layout.createSequentialGroup()
                .addGap(405, 405, 405)
                .addComponent(tambahButton, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(dashboardAdmin)
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namaKeretaLabel)
                    .addComponent(inputNamaKereta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputGerbong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gerbongLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputKelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kelasLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputJadwalBerangkat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jadwalBerangkatLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jadwalTibaLabel)
                    .addComponent(inputJadwalTiba, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputHargaTiket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hargaTiketLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stasiunAsalLabel)
                    .addComponent(inputStasiunAsal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputStasiunTujuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stasiunTujuanLabel))
                .addGap(31, 31, 31)
                .addComponent(tambahButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputGerbongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputGerbongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputGerbongActionPerformed

    private void inputNamaKeretaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputNamaKeretaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNamaKeretaActionPerformed

    private void inputKelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputKelasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputKelasActionPerformed

    private void inputJadwalBerangkatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputJadwalBerangkatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputJadwalBerangkatActionPerformed

    private void inputJadwalTibaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputJadwalTibaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputJadwalTibaActionPerformed

    private void inputHargaTiketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputHargaTiketActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputHargaTiketActionPerformed

    private void inputStasiunAsalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputStasiunAsalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputStasiunAsalActionPerformed

    private void inputStasiunTujuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputStasiunTujuanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputStasiunTujuanActionPerformed

    private void tambahButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahButtonActionPerformed
        // TODO add your handling code here:
        namaKereta = inputNamaKereta.getText();
        gerbong = inputGerbong.getText();
        kelas = inputKelas.getText();
        jadwalBerangkat = inputJadwalBerangkat.getText();
        jadwalTiba = inputJadwalTiba.getText();
        String hargaTikets = inputHargaTiket.getText();
        hargaTiket = Integer.parseInt(hargaTikets);
        stasiunAsal = inputStasiunAsal.getText();
        stasiunTujuan = inputStasiunTujuan.getText();
        
        Admin admin = new Admin();
        int addItem = JOptionPane.showConfirmDialog(null, "Apakah data kereta sudah benar?",
                    "Warning", JOptionPane.YES_NO_OPTION);
        if (addItem == JOptionPane.YES_OPTION){
            admin.membuatKereta(idKereta, namaKereta, gerbong, kelas, jadwalBerangkat, jadwalTiba, hargaTiket,stasiunAsal, stasiunTujuan);    
        }
    }//GEN-LAST:event_tambahButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //update
        int selectedRows = jTable1.getSelectedRow();
        String namaKereta = inputNamaKereta.getText().toString();
        String gerbong = inputGerbong.getText().toString();
        String kelas = inputKelas.getText().toString();
        String jadwalBerangkat = inputJadwalBerangkat.getText().toString();
        String jadwalTiba = inputJadwalTiba.getText().toString();
        String hargaTikets = inputHargaTiket.getText().toString();
        int hargaTiket = Integer.parseInt(hargaTikets);
        String stasiunAsal = inputStasiunAsal.getText().toString();
        String stasiunTujuan = inputStasiunTujuan.getText().toString();
            
        System.out.println(selectedRows);
        if(selectedRows <0){
            JOptionPane.showMessageDialog(this, "Silahkan pilih tabel kereta terlebih dahulu !", "Error", JOptionPane.ERROR_MESSAGE);
        }else{
            int editItem = JOptionPane.showConfirmDialog(null, "Yakin ingin mengedit kereta ?",
       "Warning", JOptionPane.YES_NO_OPTION);
            if(editItem == JOptionPane.YES_OPTION){
                DefaultTableModel RecordTable = (DefaultTableModel)jTable1.getModel();
                idKereta = Integer.parseInt(RecordTable.getValueAt(selectedRows, 0).toString());
                Admin admin = new Admin();
                admin.updateKereta(idKereta, namaKereta, gerbong, kelas, jadwalBerangkat, jadwalTiba, hargaTiket,stasiunAsal, stasiunTujuan);
                
             
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int selectedRows = jTable1.getSelectedRow();
        System.out.println(selectedRows);
        if(selectedRows <0 ){
            JOptionPane.showMessageDialog(this, "Silahkan pilih data pada tabel terlebih dahulu !", "Error", JOptionPane.ERROR_MESSAGE);
        }else{
              try {
           
                 DefaultTableModel RecordTable = (DefaultTableModel)jTable1.getModel();
             idKereta = Integer.parseInt(RecordTable.getValueAt(selectedRows, 0).toString());
            int deleteItem = JOptionPane.showConfirmDialog(null, "Yakin ingin delete kereta ?",
                    "Warning", JOptionPane.YES_NO_OPTION);
            if(deleteItem == JOptionPane.YES_OPTION){
                Admin admin = new Admin();
                admin.deleteKereta(idKereta);
                
                showDaftarKereta();
            }
            
        } catch (Exception e) {
        
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        showDaftarKereta();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        DefaultTableModel RecordTable = (DefaultTableModel)jTable1.getModel();
        int selectedRows = jTable1.getSelectedRow();
        inputNamaKereta.setText(RecordTable.getValueAt(selectedRows, 1).toString());
        inputGerbong.setText(RecordTable.getValueAt(selectedRows, 2).toString());
        inputKelas.setText(RecordTable.getValueAt(selectedRows, 3).toString());
        inputJadwalBerangkat.setText(RecordTable.getValueAt(selectedRows, 4).toString());
        inputJadwalTiba.setText(RecordTable.getValueAt(selectedRows, 5).toString());
        inputHargaTiket.setText(RecordTable.getValueAt(selectedRows, 6).toString());
        inputStasiunAsal.setText(RecordTable.getValueAt(selectedRows, 7).toString());
        inputStasiunTujuan.setText(RecordTable.getValueAt(selectedRows, 8).toString());
        
    }//GEN-LAST:event_jTable1MouseClicked

    public void showDaftarKereta(){
      Connection koneksi = conn.connectDB();
        try {
            PreparedStatement ps = (PreparedStatement)koneksi.prepareStatement("SELECT * FROM kereta");
            ResultSet rs = ps.executeQuery();
            ResultSetMetaData stData = rs.getMetaData();
            q = stData.getColumnCount();
            DefaultTableModel RecordTable = (DefaultTableModel)jTable1.getModel();
            RecordTable.setRowCount(0);
            
            while(rs.next()){
                Vector columdData = new Vector();
                for(int i = 1;i <= q; i++ ){
                    columdData.add(rs.getInt("idKereta"));
                    columdData.add(rs.getString("namaKereta"));
                    columdData.add(rs.getString("gerbong"));
                    columdData.add(rs.getString("kelas"));
                    columdData.add(rs.getString("jadwalBerangkat"));
                    columdData.add(rs.getString("jadwalTiba"));
                    columdData.add(rs.getInt("hargaTiket"));
                    columdData.add(rs.getString("stasiunAsal"));
                    columdData.add(rs.getString("stasiunTujuan"));
                
                }
                RecordTable.addRow(columdData);
            }
          
          
        } catch (SQLException ex) {
            Logger.getLogger(Penumpang.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashboardAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashboardAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashboardAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashboardAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashboardAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dashboardAdmin;
    private javax.swing.JLabel gerbongLabel;
    private javax.swing.JLabel hargaTiketLabel;
    private javax.swing.JTextField inputGerbong;
    private javax.swing.JTextField inputHargaTiket;
    private javax.swing.JTextField inputJadwalBerangkat;
    private javax.swing.JTextField inputJadwalTiba;
    private javax.swing.JTextField inputKelas;
    private javax.swing.JTextField inputNamaKereta;
    private javax.swing.JTextField inputStasiunAsal;
    private javax.swing.JTextField inputStasiunTujuan;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel jadwalBerangkatLabel;
    private javax.swing.JLabel jadwalTibaLabel;
    private javax.swing.JLabel kelasLabel;
    private javax.swing.JLabel namaKeretaLabel;
    private javax.swing.JLabel stasiunAsalLabel;
    private javax.swing.JLabel stasiunTujuanLabel;
    private javax.swing.JButton tambahButton;
    // End of variables declaration//GEN-END:variables
}
